platform :ios, '9.0'

target 'VialerSIPLib' do
	#pod 'VialerSIPLib', :path => '../'
    pod 'HDLumberjackLogFormatter'
    #, :git => 'https://hd-apps@bitbucket.org/hd-apps/hdlumberjacklogformatter.git'
    pod 'Vialer-pjsip-iOS'
end

target 'VialerSIPLibTests' do

end

